variable "region_name" {}
variable "vpc-cidr_block" {}
variable "vpc_tag" {}
variable "subnet-cidr-block" {}
variable "subnet_az" {}
variable "subnet_tag" {}
variable "igw_tag" {}
variable "rt_cidr_block" {}
variable "rt_tag" {}
variable "ec2_az" {}
variable "ec2_type" {}
variable "ec2_key_name" {}